local status_ok, indent_blankline = pcall(require, "indent_blankline")
if not status_ok then
  return
end

indent_blankline.setup({
  char = "▏",
  space_char_blankline = "·",
  char_list = { "|", "¦", "┆", "┊" },
  char_list_blankline = { "|", "¦", "┆", "┊" },
  show_trailing_blankline_indent = false,
  show_first_indent_level = true,
  use_treesitter = true,
	use_treesitter_scope = true,
  show_current_context = true,
  buftype_exclude = { "terminal", "nofile" },
  filetype_exclude = {
    "help",
    "packer",
    "NvimTree",
  },
	context_patterns = {
		"class",
		"return",
		"^func",
		"method",
		"^if",
		"^while",
		"element",
		"^for",
		"with",
		"try",
		"except",
		"object",
		"^table",
		"tuple",
		"block",
		"dictionary",
		"arguments",
		"arguments_list",
		"if_statement",
		"else_clause",
		"jsx_element",
		"jsx_self_closing_element",
		"try_statement",
		"catch_clause",
		"import_statement",
		"operation_type",
	},
})
