require("user.notify")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
-- require("user.bufferline")
require("user.web-devicons")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.cursorline")
require("user.colorizer")
require("user.illuminate")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.lsp")
-- require("user.lsp.null-ls")
require("user.dap")
require("user.glow")
require("user.leap")
require("user.hover")
require("user.trouble")
require("user.surround")
-- require("user.lspsaga")
require("user.jaq")
require("user.zen")
require("user.twilight")
require("user.cheat")
-- require("user.signature")
-- require("user.navigator")
