local M = {
  "lukas-reineke/indent-blankline.nvim",
  event = "BufReadPre",
  opts = {
    indentLine_enabled = 1,
    char = "▏",
  space_char_blankline = "·",
  char_list = { "|", "¦", "┆", "┊" },
  char_list_blankline = { "|", "¦", "┆", "┊" },
  show_trailing_blankline_indent = false,
  show_first_indent_level = true,
  use_treesitter = true,
  use_treesitter_scope = true,
  show_current_context = true,
  buftype_exclude = { "terminal", "nofile" },
    filetype_exclude = {
      "startify",
      "dashboard",
      "dotooagenda",
      "log",
      "fugitive",
      "gitcommit",
      "packer",
      "vimwiki",
      "markdown",
      "json",
      "txt",
      "vista",
      "help",
      "todoist",
      "NvimTree",
      "neo-tree",
      "peekaboo",
      "git",
      "TelescopePrompt",
      "undotree",
      "flutterToolsOutline",
      "", -- for all buffers without a file type
    },
    context_patterns = {
        "class",
		"return",
		"^func",
		"method",
		"^if",
		"^while",
		"element",
		"^for",
		"with",
		"try",
		"except",
		"object",
		"^table",
		"tuple",
		"block",
		"dictionary",
		"arguments",
		"arguments_list",
		"if_statement",
		"else_clause",
		"jsx_element",
		"jsx_self_closing_element",
		"try_statement",
		"catch_clause",
		"import_statement",
		"operation_type",
    },
  },
}

return M
